ALTER TABLE tabela_de_vendedores ADD PRIMARY KEY (MATRICULA);

ALTER TABLE tabela_de_vendedores ADD COLUMN (DATA_ADIMISSÃO DATE, DE_FERIAS BIT(1));

SELECT * FROM tabela_de_vendedores;
#ALTER TABLE tabela_de_vendedores CHANGE DATA_ADIMISSÃO DATA_ADMISSÃO DATE;

UPDATE tabela_de_vendedores SET DATA_ADMISSÃO = '2014-08-15', DE_FERIAS = 0 WHERE MATRICULA = '00235';
UPDATE tabela_de_vendedores SET DATA_ADMISSÃO = '2013-09-17', DE_FERIAS = 1 WHERE MATRICULA = '00236';
UPDATE tabela_de_vendedores SET PERCENTUAL_COMISSAO = '8%' WHERE MATRICULA = '00236';


INSERT INTO tabela_de_vendedores (MATRICULA, NOME, PERCENTUAL_COMISSAO, DATA_ADMISSÃO, DE_FERIAS)
VALUES('00237', 'Roberta Martins', '11%', '2017-03-18', 1);

INSERT INTO tabela_de_vendedores (MATRICULA, NOME, PERCENTUAL_COMISSAO, DATA_ADMISSÃO, DE_FERIAS)
VALUES('00238', 'Péricles Alves', '11%', '2016-08-21', 0);